### PR TITLE
update make_proto_file.py and read_display_proto_file.py

### PR DESCRIPTION
**Pull request by keshav2904**

### CODE REVIEW

**Comment by shreybatra** [comment]
@keshav2904 did u run and test it?

**Comment by keshav2904** [comment]
no i didn't.
i would like to run and test it but i don't understand how do i make a .proto file with the schema of my request/response classes. as you said in the first point.

**Comment by shreybatra** [comment]
An example is already given for you to run and test the project. ```addressbook.proto```

**Comment by keshav2904** [comment]
how do i install protoc compiler on windows? i searched but couldn't fiigure it out

**Comment by shreybatra** [comment]
you can use this [link](https://developers.google.com/protocol-buffers/docs/downloads).

**Comment by keshav2904** [comment]
when i run the make_proto_file.py file, it shows the error "No module named google"... please help.

**Comment by shreybatra** [comment]
Are you sure you installed Protoc compiler as well as protobuf package of python? 

```pip install protobuf```

**Comment by keshav2904** [comment]
Thank you.. i have successfully tested it.

**Pull request merged**
